fix: refactoring2
4rchi-nv/harrypotterapi pull request #1
Opened 2023-12-07 19:39 UTC by 4rchi-nv

2023-12-07 19:43 UTC, 4rchi-nv reviewed
Зарефакторил: вынес в отдельные файлики, включил axios, заюзал customHooks. Все работает

2023-12-07 19:43 UTC, 4rchi-nv commented
все збс

2023-12-07 19:45 UTC, 4rchi-nv reviewed
все работает

2023-12-07 19:45 UTC, 4rchi-nv commented on src/components/movies/movies.jsx
> -                console.log(data);
во нету консоли

2023-12-08 10:29 UTC, Plazo-09 requested changes

2023-12-08 10:29 UTC, Plazo-09 commented on src/components/movies/movies.jsx
>              {loading ? (
Вот эту пачку дивов в виде лоадера по хорошему вынести в отдельный компонент, такие мелкие вещи можно даже прям в этом же файле просто ниже написать и обернуть в memo() , это легко гуглиться посмотри как оборачивать в memo компоненты

2023-12-08 10:29 UTC, Plazo-09 commented on src/components/movies/movies.jsx
>              {loading ? (
```jsx
         <div key={movie.id} className="movie-card">
                        <img src={movie.attributes.poster} loading="lazy" alt={movie.attributes.title} />
                        <div className="movie-details">
                            <h2>{movie.attributes.title}</h2>
                            <p className="summary">&emsp;{movie.attributes.summary}</p>
                            <p><span>Box office: </span><span>{movie.attributes.box_office}</span></p>
                            <p><span>Budget: </span><span>{movie.attributes.budget}</span></p>
                            <p><span>Running time: </span><span>{movie.attributes.running_time}</span></p>
                            <a href={movie.attributes.trailer}>Look for the teaser-trailer</a>
                        </div>
                    </div>
```

Также вот этот блок лучше вынести в отдельный компонент, например MovieCard и вот этот компонент нужно вынести в отдельный файл а данные передавать через пропс

2023-12-08 10:29 UTC, Plazo-09 commented on src/index.js
чет как то странно обычно тут App ставят а не какой то один компонент, и почему ты убрал books?

2023-12-08 18:06 UTC, 4rchi-nv commented on src/index.js
в идеале стоило бы для каждого компонента сделать свой index.js, но так или иначе сделал компонент App и туда передал MoviesList.

2023-12-08 18:13 UTC, 4rchi-nv commented on src/components/movies/movies.jsx
>              {loading ? (
не совсем понял зачем тут мемо, ибо никаких изменений нету же у компонента. Но в любом случае, вот обернул в мемо

2023-12-08 18:38 UTC, 4rchi-nv commented on src/components/movies/movies.jsx
>              {loading ? (
заюзал movie как props и вынес все. Хотел спросить как можно сократить повторение movie.attibutes

2023-12-09 06:10 UTC, Plazo-09 commented on src/components/movies/movies.jsx
>              {loading ? (
```jsx
const { movie: {
id,
attributes,
}, ...rest } = props 
```

2023-12-09 06:12 UTC, Plazo-09 approved these changes
Вот видишь как намного лаконичнее и приятнее начал выглядеть код, прям каеф

2023-12-09 06:12 UTC, Plazo-09 commented on src/components/movies/movies.jsx
> +import { memo } from "react";
Збс! но лучше такие мелкие комопненты писать ниже своих основных компонентов

2023-12-09 06:14 UTC, Plazo-09 approved these changes

2023-12-09 06:14 UTC, Plazo-09 commented on src/components/movies/movies.jsx
збс

2023-12-09 18:00 UTC, 4rchi-nv commented on src/components/movies/movies.jsx
> +import { memo } from "react";
done!

2023-12-09 18:20 UTC, 4rchi-nv commented on src/components/movies/movies.jsx
>              {loading ? (
слишком логично и вообще было изи, но я как то всегда все усложняю. но резалт норм

2023-12-11 05:20 UTC, merged